// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judgements.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProblemId            string   `protobuf:"bytes,2,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	SubmissionId         uint64   `protobuf:"varint,3,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	JudgementId          uint64   `protobuf:"varint,4,opt,name=judgement_id,json=judgementId,proto3" json:"judgement_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{0}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListRequest) GetProblemId() string {
	if m != nil {
		return m.ProblemId
	}
	return ""
}

func (m *ListRequest) GetSubmissionId() uint64 {
	if m != nil {
		return m.SubmissionId
	}
	return 0
}

func (m *ListRequest) GetJudgementId() uint64 {
	if m != nil {
		return m.JudgementId
	}
	return 0
}

type ListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{1}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

type SubmitJudgementRequest struct {
	SubmissionId         uint64   `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	PublicSpace          string   `protobuf:"bytes,2,opt,name=public_space,json=publicSpace,proto3" json:"public_space,omitempty"`
	PrivateSpace         string   `protobuf:"bytes,3,opt,name=private_space,json=privateSpace,proto3" json:"private_space,omitempty"`
	UserSpace            string   `protobuf:"bytes,4,opt,name=user_space,json=userSpace,proto3" json:"user_space,omitempty"`
	TestCase             string   `protobuf:"bytes,5,opt,name=test_case,json=testCase,proto3" json:"test_case,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitJudgementRequest) Reset()         { *m = SubmitJudgementRequest{} }
func (m *SubmitJudgementRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitJudgementRequest) ProtoMessage()    {}
func (*SubmitJudgementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{2}
}

func (m *SubmitJudgementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitJudgementRequest.Unmarshal(m, b)
}
func (m *SubmitJudgementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitJudgementRequest.Marshal(b, m, deterministic)
}
func (m *SubmitJudgementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitJudgementRequest.Merge(m, src)
}
func (m *SubmitJudgementRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitJudgementRequest.Size(m)
}
func (m *SubmitJudgementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitJudgementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitJudgementRequest proto.InternalMessageInfo

func (m *SubmitJudgementRequest) GetSubmissionId() uint64 {
	if m != nil {
		return m.SubmissionId
	}
	return 0
}

func (m *SubmitJudgementRequest) GetPublicSpace() string {
	if m != nil {
		return m.PublicSpace
	}
	return ""
}

func (m *SubmitJudgementRequest) GetPrivateSpace() string {
	if m != nil {
		return m.PrivateSpace
	}
	return ""
}

func (m *SubmitJudgementRequest) GetUserSpace() string {
	if m != nil {
		return m.UserSpace
	}
	return ""
}

func (m *SubmitJudgementRequest) GetTestCase() string {
	if m != nil {
		return m.TestCase
	}
	return ""
}

type SubmitJudgementResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Score                uint64   `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitJudgementResponse) Reset()         { *m = SubmitJudgementResponse{} }
func (m *SubmitJudgementResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitJudgementResponse) ProtoMessage()    {}
func (*SubmitJudgementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{3}
}

func (m *SubmitJudgementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitJudgementResponse.Unmarshal(m, b)
}
func (m *SubmitJudgementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitJudgementResponse.Marshal(b, m, deterministic)
}
func (m *SubmitJudgementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitJudgementResponse.Merge(m, src)
}
func (m *SubmitJudgementResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitJudgementResponse.Size(m)
}
func (m *SubmitJudgementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitJudgementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitJudgementResponse proto.InternalMessageInfo

func (m *SubmitJudgementResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_success
}

func (m *SubmitJudgementResponse) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

type FetchFileHashRequest struct {
	ProblemId            string   `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchFileHashRequest) Reset()         { *m = FetchFileHashRequest{} }
func (m *FetchFileHashRequest) String() string { return proto.CompactTextString(m) }
func (*FetchFileHashRequest) ProtoMessage()    {}
func (*FetchFileHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{4}
}

func (m *FetchFileHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchFileHashRequest.Unmarshal(m, b)
}
func (m *FetchFileHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchFileHashRequest.Marshal(b, m, deterministic)
}
func (m *FetchFileHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchFileHashRequest.Merge(m, src)
}
func (m *FetchFileHashRequest) XXX_Size() int {
	return xxx_messageInfo_FetchFileHashRequest.Size(m)
}
func (m *FetchFileHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchFileHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchFileHashRequest proto.InternalMessageInfo

func (m *FetchFileHashRequest) GetProblemId() string {
	if m != nil {
		return m.ProblemId
	}
	return ""
}

func (m *FetchFileHashRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type FetchFileHashResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Sha1                 string   `protobuf:"bytes,2,opt,name=sha1,proto3" json:"sha1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchFileHashResponse) Reset()         { *m = FetchFileHashResponse{} }
func (m *FetchFileHashResponse) String() string { return proto.CompactTextString(m) }
func (*FetchFileHashResponse) ProtoMessage()    {}
func (*FetchFileHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{5}
}

func (m *FetchFileHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchFileHashResponse.Unmarshal(m, b)
}
func (m *FetchFileHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchFileHashResponse.Marshal(b, m, deterministic)
}
func (m *FetchFileHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchFileHashResponse.Merge(m, src)
}
func (m *FetchFileHashResponse) XXX_Size() int {
	return xxx_messageInfo_FetchFileHashResponse.Size(m)
}
func (m *FetchFileHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchFileHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchFileHashResponse proto.InternalMessageInfo

func (m *FetchFileHashResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_success
}

func (m *FetchFileHashResponse) GetSha1() string {
	if m != nil {
		return m.Sha1
	}
	return ""
}

type FetchJudgeFileRequest struct {
	FileSpace            string   `protobuf:"bytes,1,opt,name=file_space,json=fileSpace,proto3" json:"file_space,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchJudgeFileRequest) Reset()         { *m = FetchJudgeFileRequest{} }
func (m *FetchJudgeFileRequest) String() string { return proto.CompactTextString(m) }
func (*FetchJudgeFileRequest) ProtoMessage()    {}
func (*FetchJudgeFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{6}
}

func (m *FetchJudgeFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchJudgeFileRequest.Unmarshal(m, b)
}
func (m *FetchJudgeFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchJudgeFileRequest.Marshal(b, m, deterministic)
}
func (m *FetchJudgeFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchJudgeFileRequest.Merge(m, src)
}
func (m *FetchJudgeFileRequest) XXX_Size() int {
	return xxx_messageInfo_FetchJudgeFileRequest.Size(m)
}
func (m *FetchJudgeFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchJudgeFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchJudgeFileRequest proto.InternalMessageInfo

func (m *FetchJudgeFileRequest) GetFileSpace() string {
	if m != nil {
		return m.FileSpace
	}
	return ""
}

func (m *FetchJudgeFileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type FetchJudgeFileResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	File                 []byte   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Sha1                 string   `protobuf:"bytes,3,opt,name=sha1,proto3" json:"sha1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchJudgeFileResponse) Reset()         { *m = FetchJudgeFileResponse{} }
func (m *FetchJudgeFileResponse) String() string { return proto.CompactTextString(m) }
func (*FetchJudgeFileResponse) ProtoMessage()    {}
func (*FetchJudgeFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{7}
}

func (m *FetchJudgeFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchJudgeFileResponse.Unmarshal(m, b)
}
func (m *FetchJudgeFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchJudgeFileResponse.Marshal(b, m, deterministic)
}
func (m *FetchJudgeFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchJudgeFileResponse.Merge(m, src)
}
func (m *FetchJudgeFileResponse) XXX_Size() int {
	return xxx_messageInfo_FetchJudgeFileResponse.Size(m)
}
func (m *FetchJudgeFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchJudgeFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchJudgeFileResponse proto.InternalMessageInfo

func (m *FetchJudgeFileResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_success
}

func (m *FetchJudgeFileResponse) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *FetchJudgeFileResponse) GetSha1() string {
	if m != nil {
		return m.Sha1
	}
	return ""
}

type FetchJudgementRequest struct {
	TestPoint            uint64   `protobuf:"varint,1,opt,name=test_point,json=testPoint,proto3" json:"test_point,omitempty"`
	TimeLimit            uint64   `protobuf:"varint,2,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	MemoryLimit          uint64   `protobuf:"varint,3,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchJudgementRequest) Reset()         { *m = FetchJudgementRequest{} }
func (m *FetchJudgementRequest) String() string { return proto.CompactTextString(m) }
func (*FetchJudgementRequest) ProtoMessage()    {}
func (*FetchJudgementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{8}
}

func (m *FetchJudgementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchJudgementRequest.Unmarshal(m, b)
}
func (m *FetchJudgementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchJudgementRequest.Marshal(b, m, deterministic)
}
func (m *FetchJudgementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchJudgementRequest.Merge(m, src)
}
func (m *FetchJudgementRequest) XXX_Size() int {
	return xxx_messageInfo_FetchJudgementRequest.Size(m)
}
func (m *FetchJudgementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchJudgementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchJudgementRequest proto.InternalMessageInfo

func (m *FetchJudgementRequest) GetTestPoint() uint64 {
	if m != nil {
		return m.TestPoint
	}
	return 0
}

func (m *FetchJudgementRequest) GetTimeLimit() uint64 {
	if m != nil {
		return m.TimeLimit
	}
	return 0
}

func (m *FetchJudgementRequest) GetMemoryLimit() uint64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

type FetchJudgementResponse struct {
	ProblemId            string   `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	TestCase             string   `protobuf:"bytes,2,opt,name=test_case,json=testCase,proto3" json:"test_case,omitempty"`
	TimeLimit            uint64   `protobuf:"varint,3,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	MemoryLimit          uint64   `protobuf:"varint,4,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	PublicSpace          string   `protobuf:"bytes,5,opt,name=public_space,json=publicSpace,proto3" json:"public_space,omitempty"`
	PrivateSpace         string   `protobuf:"bytes,6,opt,name=private_space,json=privateSpace,proto3" json:"private_space,omitempty"`
	UserSpace            string   `protobuf:"bytes,7,opt,name=user_space,json=userSpace,proto3" json:"user_space,omitempty"`
	FileIoInputName      string   `protobuf:"bytes,8,opt,name=file_io_input_name,json=fileIoInputName,proto3" json:"file_io_input_name,omitempty"`
	FileIoOutputName     string   `protobuf:"bytes,9,opt,name=file_io_output_name,json=fileIoOutputName,proto3" json:"file_io_output_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchJudgementResponse) Reset()         { *m = FetchJudgementResponse{} }
func (m *FetchJudgementResponse) String() string { return proto.CompactTextString(m) }
func (*FetchJudgementResponse) ProtoMessage()    {}
func (*FetchJudgementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{9}
}

func (m *FetchJudgementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchJudgementResponse.Unmarshal(m, b)
}
func (m *FetchJudgementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchJudgementResponse.Marshal(b, m, deterministic)
}
func (m *FetchJudgementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchJudgementResponse.Merge(m, src)
}
func (m *FetchJudgementResponse) XXX_Size() int {
	return xxx_messageInfo_FetchJudgementResponse.Size(m)
}
func (m *FetchJudgementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchJudgementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchJudgementResponse proto.InternalMessageInfo

func (m *FetchJudgementResponse) GetProblemId() string {
	if m != nil {
		return m.ProblemId
	}
	return ""
}

func (m *FetchJudgementResponse) GetTestCase() string {
	if m != nil {
		return m.TestCase
	}
	return ""
}

func (m *FetchJudgementResponse) GetTimeLimit() uint64 {
	if m != nil {
		return m.TimeLimit
	}
	return 0
}

func (m *FetchJudgementResponse) GetMemoryLimit() uint64 {
	if m != nil {
		return m.MemoryLimit
	}
	return 0
}

func (m *FetchJudgementResponse) GetPublicSpace() string {
	if m != nil {
		return m.PublicSpace
	}
	return ""
}

func (m *FetchJudgementResponse) GetPrivateSpace() string {
	if m != nil {
		return m.PrivateSpace
	}
	return ""
}

func (m *FetchJudgementResponse) GetUserSpace() string {
	if m != nil {
		return m.UserSpace
	}
	return ""
}

func (m *FetchJudgementResponse) GetFileIoInputName() string {
	if m != nil {
		return m.FileIoInputName
	}
	return ""
}

func (m *FetchJudgementResponse) GetFileIoOutputName() string {
	if m != nil {
		return m.FileIoOutputName
	}
	return ""
}

type ReturnJudgementRequest struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Score                uint64   `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnJudgementRequest) Reset()         { *m = ReturnJudgementRequest{} }
func (m *ReturnJudgementRequest) String() string { return proto.CompactTextString(m) }
func (*ReturnJudgementRequest) ProtoMessage()    {}
func (*ReturnJudgementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{10}
}

func (m *ReturnJudgementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnJudgementRequest.Unmarshal(m, b)
}
func (m *ReturnJudgementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnJudgementRequest.Marshal(b, m, deterministic)
}
func (m *ReturnJudgementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnJudgementRequest.Merge(m, src)
}
func (m *ReturnJudgementRequest) XXX_Size() int {
	return xxx_messageInfo_ReturnJudgementRequest.Size(m)
}
func (m *ReturnJudgementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnJudgementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnJudgementRequest proto.InternalMessageInfo

func (m *ReturnJudgementRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_success
}

func (m *ReturnJudgementRequest) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ReturnJudgementRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReturnJudgementResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnJudgementResponse) Reset()         { *m = ReturnJudgementResponse{} }
func (m *ReturnJudgementResponse) String() string { return proto.CompactTextString(m) }
func (*ReturnJudgementResponse) ProtoMessage()    {}
func (*ReturnJudgementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75d1ef1952898d1e, []int{11}
}

func (m *ReturnJudgementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnJudgementResponse.Unmarshal(m, b)
}
func (m *ReturnJudgementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnJudgementResponse.Marshal(b, m, deterministic)
}
func (m *ReturnJudgementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnJudgementResponse.Merge(m, src)
}
func (m *ReturnJudgementResponse) XXX_Size() int {
	return xxx_messageInfo_ReturnJudgementResponse.Size(m)
}
func (m *ReturnJudgementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnJudgementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnJudgementResponse proto.InternalMessageInfo

func (m *ReturnJudgementResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_success
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*SubmitJudgementRequest)(nil), "SubmitJudgementRequest")
	proto.RegisterType((*SubmitJudgementResponse)(nil), "SubmitJudgementResponse")
	proto.RegisterType((*FetchFileHashRequest)(nil), "FetchFileHashRequest")
	proto.RegisterType((*FetchFileHashResponse)(nil), "FetchFileHashResponse")
	proto.RegisterType((*FetchJudgeFileRequest)(nil), "FetchJudgeFileRequest")
	proto.RegisterType((*FetchJudgeFileResponse)(nil), "FetchJudgeFileResponse")
	proto.RegisterType((*FetchJudgementRequest)(nil), "FetchJudgementRequest")
	proto.RegisterType((*FetchJudgementResponse)(nil), "FetchJudgementResponse")
	proto.RegisterType((*ReturnJudgementRequest)(nil), "ReturnJudgementRequest")
	proto.RegisterType((*ReturnJudgementResponse)(nil), "ReturnJudgementResponse")
}

func init() { proto.RegisterFile("judgements.proto", fileDescriptor_75d1ef1952898d1e) }

var fileDescriptor_75d1ef1952898d1e = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0x6b, 0x27, 0xa9, 0x6f, 0xdc, 0xb4, 0x1a, 0xda, 0x3a, 0x32, 0xaa, 0x28, 0x66, 0x53,
	0x09, 0x75, 0x24, 0xca, 0x0e, 0x21, 0x24, 0xa0, 0xaa, 0x30, 0xaa, 0x4a, 0x71, 0x77, 0x6c, 0x2c,
	0x27, 0x1e, 0xda, 0x41, 0xf1, 0x03, 0xcf, 0x18, 0xc1, 0x1f, 0xb0, 0xe1, 0xa3, 0xf8, 0x0c, 0xfe,
	0x06, 0xcd, 0x23, 0xc6, 0x8f, 0x84, 0x16, 0x56, 0xf1, 0x9c, 0x7b, 0x72, 0xe7, 0xcc, 0xbd, 0xe7,
	0xce, 0xc0, 0xce, 0xa7, 0x2a, 0xb9, 0x26, 0x29, 0xc9, 0x38, 0xc3, 0x45, 0x99, 0xf3, 0xdc, 0x73,
	0x18, 0x8f, 0x79, 0xa5, 0x57, 0xfe, 0x0f, 0x03, 0xc6, 0xe7, 0x94, 0xf1, 0x90, 0x7c, 0xae, 0x08,
	0xe3, 0xc8, 0x85, 0x51, 0xc5, 0x48, 0x19, 0xd1, 0x64, 0x6a, 0x1c, 0x1a, 0x47, 0x76, 0x38, 0x14,
	0xcb, 0x20, 0x41, 0x07, 0x00, 0x45, 0x99, 0xcf, 0x16, 0x24, 0x15, 0xb1, 0x0d, 0x19, 0xb3, 0x35,
	0x12, 0x24, 0xe8, 0x11, 0x6c, 0xb1, 0x6a, 0x96, 0x52, 0xc6, 0x68, 0x9e, 0x09, 0x86, 0x79, 0x68,
	0x1c, 0x59, 0xa1, 0xf3, 0x07, 0x0c, 0x12, 0xf4, 0x10, 0x9c, 0x5a, 0x8e, 0xe0, 0x58, 0x92, 0x33,
	0xae, 0xb1, 0x20, 0xf1, 0x27, 0xe0, 0x28, 0x39, 0xac, 0xc8, 0x33, 0x46, 0xfc, 0x9f, 0x06, 0xec,
	0x5f, 0x89, 0x1c, 0xfc, 0xed, 0x92, 0xb5, 0x94, 0xda, 0xdb, 0xd2, 0x58, 0xbd, 0x65, 0x51, 0xcd,
	0x16, 0x74, 0x1e, 0xb1, 0x22, 0x9e, 0x13, 0x2d, 0x7c, 0xac, 0xb0, 0x2b, 0x01, 0x89, 0x3c, 0x45,
	0x49, 0xbf, 0xc4, 0x9c, 0x68, 0x8e, 0x29, 0x39, 0x8e, 0x06, 0x15, 0xe9, 0x00, 0x40, 0xd6, 0x45,
	0x31, 0x2c, 0x75, 0x7c, 0x81, 0xa8, 0xf0, 0x7d, 0xb0, 0x39, 0x61, 0x3c, 0x9a, 0xc7, 0x8c, 0x4c,
	0x07, 0x32, 0xba, 0x29, 0x80, 0xd7, 0x31, 0x23, 0xfe, 0x25, 0xb8, 0xbd, 0x23, 0xa8, 0xe3, 0xa1,
	0x07, 0x30, 0x54, 0xed, 0x90, 0xe2, 0x27, 0x27, 0x23, 0x7c, 0x25, 0x97, 0xa1, 0x86, 0xd1, 0x2e,
	0x0c, 0xd8, 0x3c, 0x2f, 0x95, 0x70, 0x2b, 0x54, 0x0b, 0xff, 0x3d, 0xec, 0x9e, 0x11, 0x3e, 0xbf,
	0x39, 0xa3, 0x0b, 0xf2, 0x26, 0x66, 0x37, 0xcb, 0x92, 0xb4, 0x9b, 0x64, 0x74, 0x9b, 0xe4, 0xc1,
	0xe6, 0x47, 0xba, 0x20, 0x59, 0x9c, 0x2e, 0x0b, 0x51, 0xaf, 0xfd, 0x73, 0xd8, 0xeb, 0xa4, 0xbc,
	0xab, 0x44, 0x04, 0x16, 0xbb, 0x89, 0x9f, 0xe8, 0x8c, 0xf2, 0xdb, 0x0f, 0x75, 0x36, 0x79, 0x62,
	0x91, 0xb2, 0xa1, 0x50, 0x6c, 0xa9, 0xeb, 0xa8, 0x15, 0x0a, 0x44, 0xd5, 0xf1, 0x6f, 0x0a, 0x63,
	0xd8, 0xef, 0xe6, 0xfc, 0x07, 0x89, 0x22, 0x8d, 0x4c, 0xe9, 0x84, 0xf2, 0xbb, 0x96, 0x6d, 0x36,
	0x64, 0x7f, 0x6d, 0xca, 0x6e, 0x7a, 0xed, 0x00, 0x40, 0xf6, 0xb7, 0xc8, 0x69, 0xc6, 0xb5, 0xd1,
	0x64, 0xc7, 0x2f, 0x05, 0x20, 0xc3, 0x34, 0x25, 0xd1, 0x82, 0xa6, 0x94, 0xeb, 0x56, 0xd9, 0x02,
	0x39, 0x17, 0x80, 0x30, 0x61, 0x4a, 0xd2, 0xbc, 0xfc, 0xa6, 0x09, 0x6a, 0x36, 0xc6, 0x0a, 0x93,
	0x14, 0xff, 0xd7, 0x46, 0xf3, 0x74, 0x2d, 0x8f, 0xdc, 0xd2, 0xd4, 0x96, 0xf5, 0x36, 0xda, 0xd6,
	0xeb, 0x08, 0x33, 0x6f, 0x13, 0x66, 0xf5, 0x84, 0xf5, 0x06, 0x68, 0x70, 0x87, 0x01, 0x1a, 0xde,
	0x3a, 0x40, 0xa3, 0xee, 0x00, 0x3d, 0x06, 0x24, 0x7d, 0x41, 0xf3, 0x88, 0x66, 0x45, 0xc5, 0x23,
	0x69, 0x81, 0x4d, 0x49, 0xdb, 0x16, 0x91, 0x20, 0x0f, 0x04, 0x7e, 0x11, 0xa7, 0x04, 0x1d, 0xc3,
	0xbd, 0x25, 0x39, 0xaf, 0x78, 0xcd, 0xb6, 0x25, 0x7b, 0x47, 0xb1, 0xdf, 0xc9, 0xc0, 0x85, 0x36,
	0x4e, 0x48, 0x78, 0x55, 0x66, 0xbd, 0xb6, 0xfe, 0xdf, 0xf8, 0xa1, 0x1d, 0x30, 0x53, 0x76, 0xad,
	0x9d, 0x23, 0x3e, 0xfd, 0x67, 0xe0, 0xf6, 0xb6, 0xb8, 0xa3, 0x39, 0x4f, 0xbe, 0x9b, 0x00, 0xf5,
	0xdf, 0x18, 0x3a, 0x85, 0xed, 0xce, 0x6d, 0x81, 0x5c, 0xbc, 0xfa, 0x0a, 0xf4, 0xa6, 0x78, 0xdd,
	0xc5, 0xf2, 0x02, 0xb6, 0xa4, 0x9d, 0xc4, 0x28, 0x8b, 0x59, 0x41, 0x7b, 0x78, 0xd5, 0x8d, 0xe1,
	0xed, 0xe3, 0xd5, 0x53, 0xff, 0x1c, 0xec, 0x3a, 0x80, 0x34, 0xa9, 0x3b, 0xcc, 0x9e, 0x8b, 0xd7,
	0x0c, 0xe4, 0x4b, 0x98, 0xb4, 0xcd, 0xdc, 0x4a, 0xd1, 0x3c, 0x81, 0x8b, 0xd7, 0xb8, 0xfe, 0x14,
	0xb6, 0x3b, 0x15, 0x45, 0x2e, 0x5e, 0xdd, 0x46, 0x6f, 0x8a, 0xd7, 0x15, 0xff, 0x18, 0x26, 0xe2,
	0x39, 0x69, 0x94, 0xd7, 0xc1, 0x8d, 0xe7, 0xce, 0xdb, 0xc2, 0xcd, 0xd7, 0xe6, 0xd5, 0xe8, 0xc3,
	0x40, 0x3e, 0x8b, 0xb3, 0xa1, 0xfc, 0x79, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x08, 0x38, 0xd9,
	0xe3, 0x3f, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JudgementsClient is the client API for Judgements service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JudgementsClient interface {
	SubmitJudgement(ctx context.Context, in *SubmitJudgementRequest, opts ...grpc.CallOption) (*SubmitJudgementResponse, error)
	FetchHashFile(ctx context.Context, in *FetchFileHashRequest, opts ...grpc.CallOption) (*FetchFileHashResponse, error)
	FetchFile(ctx context.Context, in *FetchJudgeFileRequest, opts ...grpc.CallOption) (*FetchJudgeFileResponse, error)
	FetchJudgement(ctx context.Context, in *FetchJudgementRequest, opts ...grpc.CallOption) (*FetchJudgementResponse, error)
	ReturnJudgement(ctx context.Context, in *ReturnJudgementRequest, opts ...grpc.CallOption) (*ReturnJudgementResponse, error)
	ListJudgements(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type judgementsClient struct {
	cc grpc.ClientConnInterface
}

func NewJudgementsClient(cc grpc.ClientConnInterface) JudgementsClient {
	return &judgementsClient{cc}
}

func (c *judgementsClient) SubmitJudgement(ctx context.Context, in *SubmitJudgementRequest, opts ...grpc.CallOption) (*SubmitJudgementResponse, error) {
	out := new(SubmitJudgementResponse)
	err := c.cc.Invoke(ctx, "/Judgements/SubmitJudgement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgementsClient) FetchHashFile(ctx context.Context, in *FetchFileHashRequest, opts ...grpc.CallOption) (*FetchFileHashResponse, error) {
	out := new(FetchFileHashResponse)
	err := c.cc.Invoke(ctx, "/Judgements/FetchHashFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgementsClient) FetchFile(ctx context.Context, in *FetchJudgeFileRequest, opts ...grpc.CallOption) (*FetchJudgeFileResponse, error) {
	out := new(FetchJudgeFileResponse)
	err := c.cc.Invoke(ctx, "/Judgements/FetchFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgementsClient) FetchJudgement(ctx context.Context, in *FetchJudgementRequest, opts ...grpc.CallOption) (*FetchJudgementResponse, error) {
	out := new(FetchJudgementResponse)
	err := c.cc.Invoke(ctx, "/Judgements/FetchJudgement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgementsClient) ReturnJudgement(ctx context.Context, in *ReturnJudgementRequest, opts ...grpc.CallOption) (*ReturnJudgementResponse, error) {
	out := new(ReturnJudgementResponse)
	err := c.cc.Invoke(ctx, "/Judgements/ReturnJudgement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgementsClient) ListJudgements(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/Judgements/ListJudgements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JudgementsServer is the server API for Judgements service.
type JudgementsServer interface {
	SubmitJudgement(context.Context, *SubmitJudgementRequest) (*SubmitJudgementResponse, error)
	FetchHashFile(context.Context, *FetchFileHashRequest) (*FetchFileHashResponse, error)
	FetchFile(context.Context, *FetchJudgeFileRequest) (*FetchJudgeFileResponse, error)
	FetchJudgement(context.Context, *FetchJudgementRequest) (*FetchJudgementResponse, error)
	ReturnJudgement(context.Context, *ReturnJudgementRequest) (*ReturnJudgementResponse, error)
	ListJudgements(context.Context, *ListRequest) (*ListResponse, error)
}

// UnimplementedJudgementsServer can be embedded to have forward compatible implementations.
type UnimplementedJudgementsServer struct {
}

func (*UnimplementedJudgementsServer) SubmitJudgement(ctx context.Context, req *SubmitJudgementRequest) (*SubmitJudgementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJudgement not implemented")
}
func (*UnimplementedJudgementsServer) FetchHashFile(ctx context.Context, req *FetchFileHashRequest) (*FetchFileHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchHashFile not implemented")
}
func (*UnimplementedJudgementsServer) FetchFile(ctx context.Context, req *FetchJudgeFileRequest) (*FetchJudgeFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchFile not implemented")
}
func (*UnimplementedJudgementsServer) FetchJudgement(ctx context.Context, req *FetchJudgementRequest) (*FetchJudgementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchJudgement not implemented")
}
func (*UnimplementedJudgementsServer) ReturnJudgement(ctx context.Context, req *ReturnJudgementRequest) (*ReturnJudgementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnJudgement not implemented")
}
func (*UnimplementedJudgementsServer) ListJudgements(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJudgements not implemented")
}

func RegisterJudgementsServer(s *grpc.Server, srv JudgementsServer) {
	s.RegisterService(&_Judgements_serviceDesc, srv)
}

func _Judgements_SubmitJudgement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJudgementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).SubmitJudgement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/SubmitJudgement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).SubmitJudgement(ctx, req.(*SubmitJudgementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judgements_FetchHashFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchFileHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).FetchHashFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/FetchHashFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).FetchHashFile(ctx, req.(*FetchFileHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judgements_FetchFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchJudgeFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).FetchFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/FetchFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).FetchFile(ctx, req.(*FetchJudgeFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judgements_FetchJudgement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchJudgementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).FetchJudgement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/FetchJudgement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).FetchJudgement(ctx, req.(*FetchJudgementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judgements_ReturnJudgement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnJudgementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).ReturnJudgement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/ReturnJudgement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).ReturnJudgement(ctx, req.(*ReturnJudgementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judgements_ListJudgements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgementsServer).ListJudgements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Judgements/ListJudgements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgementsServer).ListJudgements(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Judgements_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Judgements",
	HandlerType: (*JudgementsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJudgement",
			Handler:    _Judgements_SubmitJudgement_Handler,
		},
		{
			MethodName: "FetchHashFile",
			Handler:    _Judgements_FetchHashFile_Handler,
		},
		{
			MethodName: "FetchFile",
			Handler:    _Judgements_FetchFile_Handler,
		},
		{
			MethodName: "FetchJudgement",
			Handler:    _Judgements_FetchJudgement_Handler,
		},
		{
			MethodName: "ReturnJudgement",
			Handler:    _Judgements_ReturnJudgement_Handler,
		},
		{
			MethodName: "ListJudgements",
			Handler:    _Judgements_ListJudgements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "judgements.proto",
}
